env:
  browser: false
  commonjs: true
  es6: true
  jasmine: true
  jest: true
extends:
  - 'plugin:jasmine/recommended'
  - 'eslint:recommended'
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - jasmine
rules:
  camelcase: 0
  'arrow-body-style': 0
  'class-methods-use-this': 0
  'no-underscore-dangle': 0
  'react/destructuring-assignment': 0
  'import/no-unresolved': 0
  'consistent-return': 0
  'no-multi-spaces': 0
  'no-param-reassign': 0
  'no-throw-literal': 0
  'no-restricted-syntax': 0
  'no-console': 0
  'max-len': 0
  'no-else-return': 0
  'no-await-in-loop': 0
  'global-require': 0
  'prefer-destructuring': 0